# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaconApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beacon',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dept',
            new_name='collection',
        ),
    ]
